seed: 42
data:
  data_dir: "./data"
  batch_size: 128
  num_workers: 8
model:
  resnet: True
  n: 5
  num_classes: 10
  type: "A"
train:
  epochs: 185
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0001
